/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Luís Paulo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMeusDadosMenu = new javax.swing.JMenu();
        jMeusDadosMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jFichaTecMenuItem = new javax.swing.JMenuItem();
        jExercicioMenu = new javax.swing.JMenu();
        jCadExercMenuItem = new javax.swing.JMenuItem();
        jTreinosMenu = new javax.swing.JMenu();
        jCadTreinoMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCadTreinoMembTipoMenuItem = new javax.swing.JMenuItem();
        jDiarioMenu = new javax.swing.JMenu();
        jCadDiarioTreiMenuItem = new javax.swing.JMenuItem();
        jRelatoriosMenu = new javax.swing.JMenu();
        jConfigMenu = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyFit");
        setIconImage(new ImageIcon("./Images/MyFit.png").getImage());
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyFitMenu.jpg"))); // NOI18N

        jMenuBar1.setForeground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setToolTipText("");

        jMeusDadosMenu.setText("Meus Dados");

        jMeusDadosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMeusDadosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meusDados3.png"))); // NOI18N
        jMeusDadosMenuItem.setText("Meus Dados");
        jMeusDadosMenu.add(jMeusDadosMenuItem);
        jMeusDadosMenu.add(jSeparator3);

        jFichaTecMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jFichaTecMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ficha.png"))); // NOI18N
        jFichaTecMenuItem.setText("Ficha Técnica");
        jMeusDadosMenu.add(jFichaTecMenuItem);

        jMenuBar1.add(jMeusDadosMenu);

        jExercicioMenu.setText("Exercícios");

        jCadExercMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jCadExercMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exercicio3.png"))); // NOI18N
        jCadExercMenuItem.setText("Cadastro de exercício");
        jExercicioMenu.add(jCadExercMenuItem);

        jMenuBar1.add(jExercicioMenu);

        jTreinosMenu.setText("Treinos");

        jCadTreinoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jCadTreinoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Execicios21.png"))); // NOI18N
        jCadTreinoMenuItem.setText("Cadastro de treino diário");
        jTreinosMenu.add(jCadTreinoMenuItem);
        jTreinosMenu.add(jSeparator1);

        jCadTreinoMembTipoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/biceps.png"))); // NOI18N
        jCadTreinoMembTipoMenuItem.setText("Cadastro de treino de membro/tipo");
        jTreinosMenu.add(jCadTreinoMembTipoMenuItem);

        jMenuBar1.add(jTreinosMenu);

        jDiarioMenu.setText("Diários");

        jCadDiarioTreiMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jCadDiarioTreiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diario.png"))); // NOI18N
        jCadDiarioTreiMenuItem.setText("Cadastro de diário de treino");
        jCadDiarioTreiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadDiarioTreiMenuItemActionPerformed(evt);
            }
        });
        jDiarioMenu.add(jCadDiarioTreiMenuItem);

        jMenuBar1.add(jDiarioMenu);

        jRelatoriosMenu.setText("Relatórios");
        jMenuBar1.add(jRelatoriosMenu);

        jConfigMenu.setText("Configurações");
        jMenuBar1.add(jConfigMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadDiarioTreiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadDiarioTreiMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCadDiarioTreiMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadDiarioTreiMenuItem;
    private javax.swing.JMenuItem jCadExercMenuItem;
    private javax.swing.JMenuItem jCadTreinoMembTipoMenuItem;
    private javax.swing.JMenuItem jCadTreinoMenuItem;
    private javax.swing.JMenu jConfigMenu;
    private javax.swing.JMenu jDiarioMenu;
    private javax.swing.JMenu jExercicioMenu;
    private javax.swing.JMenuItem jFichaTecMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMeusDadosMenu;
    private javax.swing.JMenuItem jMeusDadosMenuItem;
    private javax.swing.JMenu jRelatoriosMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jTreinosMenu;
    // End of variables declaration//GEN-END:variables
}
